#!/bin/bash
# Age MMDVM log file backups
#
#xro=$(grep "/dev/root" /proc/mounts | sed -n "s/.*\(r[ow]\).*/\1/p")
xro=$(sed -n "s/\/dev\/.* \/ ext4 \(r[ow]\).*/\1/p" /proc/mounts)
#rpi-rw
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,rw / # sudo mount -o remount,rw /boot
fi
#
file=/home/pi-star/.mlogs
m0=14                             # number to be kept
if [[ $1 =~ [0-9] ]]; then
  m0=$1
fi
#
m3=0
m1=$(ls ${file}/MMDVM* | wc -l)   # total number of files
m2=$(expr ${m1} - ${m0})          # number to be deleted
mods=(MMDVM DMR APRS M17 YSF ircDDB NXDN P25 timeserverd)         # list of logs to age
#
# age by count:
for modx in ${mods[*]}; do
  m1=$(ls ${file}/${modx}* 2>/dev/null | wc -l)   # total number of files
  m2=$(expr ${m1} - ${m0})        # number to be deleted
# echo $modx $m1 $m2
  if [ ${m2} -gt 0 -a ${m0} -gt 0 ]; then
    m3=$(expr $m3 + $m2)
    filed=$(ls -tr ${file}/${modx}* | head -n ${m2})
    for f in ${filed}; do
#     echo $f
      sudo rm $f
    done
  fi
done
#
# age by date:
filed=$(find ${file}/re* -mtime +${m0} 2>/dev/null)   # del related reboot/restore msgs
for f in ${filed}; do
# echo $f
  sudo rm $f
done
logger -t "[$$]" "Pi-Star --> MMDVM log backups aged: $m3 files <--"
#
#rpi-ro
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,ro / # sudo mount -o remount,ro /boot
fi
