#!/bin/bash
#
##############################################################################
#                                                                            #
#                     Pi-Star MMDVM HS_HAT Reset Tool                        #
#                                                                            #
#     Version 1.0, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#     Make it simple to reset an MMDVM bosard from the CLI on Pi-Star.       #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

if [ -f '/etc/dstar-radio.mmdvmhost' ]; then
    # Get the modem that the user has selected.
    modemSelected=$(grep 'Hardware=' /etc/dstar-radio.mmdvmhost)
    modemSelected=${modemSelected#*=}

    # Get the user friendly version of the selected Modem.
    modemSelectedHuman=$(grep value=\"${modemSelected}\" /var/www/dashboard/admin/configure.php | head -n 1)
    modemSelectedHuman=${modemSelectedHuman#*\">}
    modemSelectedHuman=${modemSelectedHuman::-9}
    echo -e "Resetting Modem: ${modemSelectedHuman}"
fi

case ${modemSelected} in
mmdvmhshat)
  # Reset process for MMDVM HS_HAT Board
  echo 20 > /sys/class/gpio/export
  echo 21 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio20/direction
  echo out > /sys/class/gpio/gpio21/direction
  sleep 0.5
  echo 0 > /sys/class/gpio/gpio20/value
  echo 0 > /sys/class/gpio/gpio21/value
  echo 1 > /sys/class/gpio/gpio21/value
  sleep 1
  echo 0 > /sys/class/gpio/gpio20/value
  echo 1 > /sys/class/gpio/gpio20/value
  sleep 0.5
  echo 20 > /sys/class/gpio/unexport
  echo 21 > /sys/class/gpio/unexport
;;

*)
  # Nothing to do.
;;
esac

echo -e "Reset Complete"

exit 0
