#!/bin/bash
# Reconfigure/Reconnect WIFI
#
#rpi-rw:
sudo mount -o remount,rw / ; sudo mount -o remount,rw /boot
#
logger -t "[$$]" "Pi-Star --> Wifi Reconnect initiated <--"
sudo wpa_cli reconfigure wlan0
sudo ifdown wlan0
sleep 3
sudo ifup wlan0
sudo wpa_cli scan
#
#rpi-ro:
sudo mount -o remount,ro / ; sudo mount -o remount,ro /boot
