#!/bin/bash
#
##############################################################################
#                                                                            #
#                      Pi-Star YSFGateway link Tool                          #
#                                                                            #
#     Version 1.0, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#         Make it simple to link reflectors from the CLI on Pi-Star.         #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Make sure config is present
if [ "$(grep -o 'Remote Commands' /etc/ysfgateway | wc -l)" -eq "0" ]; then
  echo -e "Remote Commands not enabled...\n"
  exit 1
fi

# Setup some variables
cmd=/usr/local/bin/RemoteCommand
enable=$(sed -n '/^\[Remote Commands\]/,/^\[/p' /etc/ysfgateway | grep "^Enable" | awk -F '=' '{print $2}')
port=$(sed -n '/^\[Remote Commands\]/,/^\[/p' /etc/ysfgateway | grep "^Port" | awk -F '=' '{print $2}')

# Make sure that remote commands are turned on
if [ "${enable}" -eq "0" ]; then
  echo -e "Remote Commands not enabled...\n"
  exit 1
fi


if [ -z "$1" ]
then
      echo "To unlink from any connected reflector, use: pistar-ysflink unlink"
      echo "To link to YSF31672, use: pistar-ysflink ysf31672"
      echo "To link to FCS002-90, use: pistar-ysflink fcs00290"
      echo ""
      exit 0
fi

case ${1} in
unlink)
  (cd /var/log/pi-star/; ${cmd} ${port} UnLink)
  exit 0
;;
*)
  if [ ${#1} -ne 8 ]; then
    echo -e "Invalid target ${1}"
    exit 1
  fi
  (cd /var/log/pi-star/; ${cmd} ${port} Link${1^^})
  exit 0
;;
esac

exit 0
