#!/bin/bash
# -*- mode: shell-script; -*-

# Script that manage few things on Pi-Star
# Copyright (C) 2019-2020 F1RMB - Daniel Caujolle-Bert <f1rmb.daniel@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#

if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

VERSION_STRING="0.0.3"
BACKUP_ROOT_DIR="/var/backups/pistar"
BACKUP_CATALOG="$BACKUP_ROOT_DIR/catalog"

## Remount FS RW mode
function _rw() {
    mount -o remount,rw /
    mount -o remount,rw /boot
}

## Remount FS RO mode
function _ro() {
    sync
    mount -o remount,ro /boot
    mount -o remount,ro /
}

## Handles Ctrl-C keystroke
function CtrlC() {
    echo -ne "\n   <Ctrl-C> has been pressed. Do you want to quit (y/N) ?> "
    read c
    
    case "$c" in
	y|yes|Y|YES)
	    exit 1
	    ;;
	
	*)
	    return 0
	    ;;
    esac
}

## Function that does nothing
function CtrlC_NOOP() {
    :
}

## Handled menu choice
function MenuPrompt() {
    echo "   q: Exit"
    echo -n "?> "
    read r
    
    re='^[0-9]+$'

    if [ -z "$r" ]; then
	return -1
    elif [[ $r =~ $re ]] && [ "$r" -ge 0 -a "$r" -lt 99 ]; then
	return "$r"
    else
	return $(printf '%d' "'$r")
    fi
}

## Services menu
function MenuServices() {
    while true; do
	echo -e "\n   Services:"
	echo "   --------"
	echo "   1: Start Services"
	echo "   2: Stop Services"
	echo "   3: Full Stop Services"
	echo "   4: Restart Services"
	echo "   5: Services Status."
	MenuPrompt
	r=$?
	
	case "$r" in
	    1)
		/usr/local/sbin/pistar-services start
		echo "[OK]"
		;;

	    2)
		/usr/local/sbin/pistar-services stop
		echo "[OK]"
		;;

	    3)
		/usr/local/sbin/pistar-services fullstop
		echo "[OK]"
		;;

	    4)
		/usr/local/sbin/pistar-services restart
		echo "[OK]"
		;;

	    5)
		/usr/local/sbin/pistar-services status
		echo "[OK]"
		;;

	    113|81)
		break
		;;
	esac
    done
}

## Rebuild backup catalog (removes empty backup entries)
function RebuildBackupCatalog() {
    if [ -f $BACKUP_CATALOG -a -s $BACKUP_CATALOG ]; then
	declare -a lines
	
	while read l; do
	    lines+=("$l")
	done < $BACKUP_CATALOG
	
	_rw
	let n=0
	for l in "${lines[@]}"; do
	    location=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')
	    
	    if [ ! -e "$BACKUP_ROOT_DIR/$location/config_backup.zip" ] || [ -e "$BACKUP_ROOT_DIR/$location/config_backup.zip" -a ! -s "$BACKUP_ROOT_DIR/$location/config_backup.zip" ]; then
		rm -rf $BACKUP_ROOT_DIR/$location/config_backup.zip > /dev/null 2>&1
		rmdir $BACKUP_ROOT_DIR/$location > /dev/null 2>&1
		unset 'lines[n]'
	    fi
	    
	    ((n++))
	done
	
	rm -f $BACKUP_CATALOG > /dev/null 2>&1
	for l in "${lines[@]}"; do
	    echo "$l" >> $BACKUP_CATALOG
	done

	# Sort the catalog
	sort -t ':' -k1g,1 -o $BACKUP_CATALOG < $BACKUP_CATALOG

	_ro
	
    fi
}

## Execute backup. Add or replace existing ones
function DoBackup() {
    backupName="$1"
    oldTS="$2"
    backupDir="/tmp/config_backup"
    backupZip="/tmp/config_backup.zip"
    
    echo -n "Backing files up..."

    rm -rf $backupZip > /dev/null 2>&1
    rm -rf $backupDir > /dev/null 2>&1
    mkdir -p $backupDir > /dev/null 2>&1
    
    if [ -f /etc/dhcpcd.conf ]; then
	if [ ! -z "`cat /etc/dhcpcd.conf | grep \"static ip_address\" | grep -v \"#\"`" ]; then
            cp /etc/dhcpcd.conf $backupDir > /dev/null 2>&1
	fi
    fi
    
    files=("/etc/wpa_supplicant/wpa_supplicant.conf" "/etc/pistar-css.ini" "/etc/ircddbgateway" "/etc/mmdvmhost" "/etc/dstarrepeater" "/etc/dapnetgateway"
	   "/etc/p25gateway" "/etc/ysfgateway" "/etc/nxdngateway" "/etc/ysf2dmr" "/etc/dmrgateway" "/etc/starnetserver" "/etc/timeserver" "/etc/dstar-radio.*"
	   "/etc/pistar-remote" "/etc/hosts" "/etc/hostname" "/etc/bmapi.key" "/etc/dapnetapi.key" "/etc/aprsgateway" "/etc/default/gpsd"
	   "/etc/tinyfilemanager-auth.php" "/etc/tinyfilemanager-config.php" "/usr/local/etc/RSSI.dat"
	   "/var/www/dashboard/config/ircddblocal.php" "/var/www/dashboard/config/config.php" "/var/www/dashboard/config/language.php"
	   "/root/*Hosts.txt")
    
    # Copy files
    for f in "${files[@]}"; do
	cp -f $f $backupDir > /dev/null 2>&1
    done
    
    zip -j $backupZip $backupDir/* > /dev/null 2>&1

    timestamp=$(date +"%Y-%m-%d_%H-%M-%S")

    _rw
    
    mkdir -p $BACKUP_ROOT_DIR/$timestamp
    mv $backupZip $BACKUP_ROOT_DIR/$timestamp

    echo -e "\b\b\b: DONE."
    
    ## Add entry, or replace entry (according to $2), to the catalog
    if [ -z "$oldTS" ]; then
	echo "$backupName:$timestamp" >> $BACKUP_CATALOG
    else
	declare -a lines
	
	while read l; do
	    lines+=("$l")
	done < $BACKUP_CATALOG
	
	rm -f $BACKUP_CATALOG > /dev/null 2>&1
	
	for l in "${lines[@]}"; do
	    name=$(echo "$l" | awk 'BEGIN { FS=":" } { print $1 }')
	    location=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')

	    ## Change location for this one
	    if [[ "$oldTS" == "$location" ]]; then
		echo "$name:$timestamp" >> $BACKUP_CATALOG
	    else
		echo "$l" >> $BACKUP_CATALOG
	    fi

	done
    fi

    # Sort the catalog
    sort -t ':' -k1g,1 -o $BACKUP_CATALOG < $BACKUP_CATALOG
    
    _ro
    
    echo "[OK] ** \"$backupName\" backed up."
}

## Lookup for backup location matching name ($1)
function LookupBackup() {
    n="$1"
    if [ -f $BACKUP_CATALOG ]; then
	while read l; do
	    name=$(echo "$l" | awk 'BEGIN { FS=":" } { print $1 }')
	    location=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')
	    
	    if [[ "$n" == "$name" ]]; then
		echo "$location"
		return 0
	    fi
	done < $BACKUP_CATALOG
    fi
    
    # Not found
    echo ""
    return 1
}

## Backup current configuration
function BackupCurrentConfig() {
    replaceTS=""

    while true; do
	if [ -z "$1" ]; then
	    echo -n "Give a name to this backup (no colon ':' allowed) ?> "
	    read a
	else
	    a="$1"
	fi
	
	if [ ! -z "$a" ]; then
	    
	    ## Lookup existing backup with same name
	    r=$(echo "$a" | tr -s \: _)
	    b=$(LookupBackup "$r")

	    if [ -z "$b" ]; then
		break
	    else
		if [ -z "$1" ]; then
		    ## Exist. Replace ?
		    echo -n "A backup with the same name already exists (timestamp: $b), do you want to override it ? (y/N): ?> "
		    read ov
		else
		    ov="Y"
		fi
		    
		case "$ov" in
		    "y"|"Y")
			## Remove old backup dir
			_rw
			rm -rf $BACKUP_ROOT_DIR/$b > /dev/null 2>&1
			_ro
			replaceTS="$b"
			break
			;;
		esac
		##echo -e "[ERR] ** A backup with an identical name already exists. Name it differently.\n"
	    fi
	else
	    ##echo -e "[ERR] ** Empty name isn't allowed.\n"
	    # Cancel
	    echo "[OK] ** Canceled"
	    return 1
	fi
    done

    if [ ! -z "$1" ]; then
	echo "Backing up \"$r\"."
    fi
    DoBackup "$r" "$replaceTS"
}

## List all available backups
function ListAvailableBackups() {
    echo -e "\n   Available backups:"
    echo "   -----------------"
    if [ -f $BACKUP_CATALOG -a -s $BACKUP_CATALOG ]; then
	let n=0
	while read l; do
	    name=$(echo "$l" | awk 'BEGIN { FS=":" } { print $1 }')
	    location=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')

	    if [ ! -z "$name" -a -e "$BACKUP_ROOT_DIR/$location/config_backup.zip" -a -s "$BACKUP_ROOT_DIR/$location/config_backup.zip" ]; then
		if [ "$1" == "count" ]; then
		    echo " $n -> \"$name\" (timestamp: $location)"
		    ((n++))
		else
		    echo "     -> \"$name\" (timestamp: $location)"
		fi
	    fi
	done < $BACKUP_CATALOG
    else
	echo "[NONE]"
    fi
}

## Execute backup restoration, restarts services
function DoRestore() {
    backupLocation="$BACKUP_ROOT_DIR/$1"    
    backupName="$2"
    restoreDir="/tmp/config_restore"
    
    rm -rf $restoreDir > /dev/null 2>&1
    mkdir -p $restoreDir > /dev/null 2>&1
    unzip $backupLocation/config_backup.zip -d $restoreDir > /dev/null 2>&1

    /usr/local/sbin/pistar-services fullstop

    echo -n "Restoring files..."
    _rw
    
    ## Moving files
    rm -f /etc/dstar-radio.* > /dev/null 2>&1
    mv -f /tmp/config_restore/RSSI.dat /usr/local/etc/ > /dev/null 2>&1
    mv -f /tmp/config_restore/gpsd /etc/default/ > /dev/null 2>&1
    mv -f /tmp/config_restore/ircddblocal.php /var/www/dashboard/config/ > /dev/null 2>&1
    mv -f /tmp/config_restore/config.php /var/www/dashboard/config/ > /dev/null 2>&1
    mv -f /tmp/config_restore/language.php /var/www/dashboard/config/ > /dev/null 2>&1
    mv -f /tmp/config_restore/*Hosts.txt /root/ > /dev/null 2>&1
    mv -v -f /tmp/config_restore/wpa_supplicant.conf /etc/wpa_supplicant/ > /dev/null 2>&1
    mv -v -f /tmp/config_restore/* /etc/ > /dev/null 2>&1
    
    ## Restore the timezone
    timeZone=$(grep date /var/www/dashboard/config/config.php | grep -o "'.*'" | sed "s/'//g")
    timedatectl set-timezone $timeZone
    
    ## Restore ircDDGBateway link manager password
    ircRemotePassword=$(grep remotePassword /etc/ircddbgateway | awk -F'=' '{print $2}')
    sed -i "/password=/c\\password=$ircRemotePassword" /root/.Remote\ Control

    ## Updating hostfiles
    /usr/local/sbin/HostFilesUpdate.sh
    
    _ro

    echo -e "\b\b\b: DONE."
    
    /usr/local/sbin/pistar-services start
    if [ "$(grep "pistar-upnp.service" /etc/crontab | cut -c 1)" != "#" ]; then
	systemctl start pistar-upnp.service > /dev/null 2>&1
    fi
    systemctl start cron.service > /dev/null 2>&1

    echo "[OK] ** \"$backupName\" restored."
}

## Menu to select a backup to restore
function RestoreBackup() {
    if [ -z "$1" ]; then
	echo -e "\n   Available backups:"
	echo "   -----------------"
    fi
    
    if [ -f $BACKUP_CATALOG -a -s $BACKUP_CATALOG ]; then
	let n=0
	declare -a names locations
	offsetToRestore=""
	nameToRestore=""

	if [ ! -z "$1" ]; then
	    re='^[0-9]+$'
	    if ! [[ $1 =~ $re ]] ; then
		nameToRestore="$1"
	    else
		numberToRestore="$1"
	    fi
	fi

	
	while read l; do
	    names[n]=$(echo "$l" | awk 'BEGIN { FS=":" } { print $1 }')
	    locations[n]=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')
	    
	    if [ -z "$1" ]; then
		echo "     $n -> \"${names[n]}\" (timestamp: ${locations[n]})"
	    else
		if [ ! -z "$nameToRestore" -a -z "$numberToRestore" ]; then
		    if [[ "$nameToRestore" == "${names[n]}" ]]; then
			numberToRestore=$n
		    fi
		fi
	    fi
	    
	    ((n++))
	done < $BACKUP_CATALOG

	if [ -z "$1" ]; then
	    echo "    [EMPTY] -> Cancels Operation"
	    echo "Enter the number to restore"
	    echo -n "?> "
	    
	    read o

	else
	    o=$numberToRestore
	fi
	    
 	let offset=-1
	
	if [ ! -z $o ]; then
	    offset=$(($o))
	fi
	
	# Check in boundaries
	if [ $offset -ge 0 -a $offset -lt ${#locations[@]} ]; then
	    if [ ! -z "$1" ]; then
		echo "Restoring \"${names[offset]}\"."
	    fi
	    DoRestore "${locations[offset]}" "${names[offset]}"
	fi
    else
	echo "[NONE]"
    fi
}

## Menu to select a backup to delete
function DeleteBackup() {
    echo -e "\n   Available backups:"
    echo "   -----------------"
    if [ -f $BACKUP_CATALOG -a -s $BACKUP_CATALOG ]; then
	let n=0
	declare -a names locations
	
	while read l; do
	    names[n]=$(echo "$l" | awk 'BEGIN { FS=":" } { print $1 }')
	    locations[n]=$(echo "$l" | awk 'BEGIN { FS=":" } { print $2 }')
	    echo "     $n -> \"${names[n]}\" (timestamp: ${locations[n]})"

	    ((n++))
	done < $BACKUP_CATALOG

	echo "    [EMPTY] -> Cancels Operation"
	echo "Enter the number to delete"
	echo -n "?> "
	
	read o
	let offset=-1

	if [ ! -z $o ]; then
	    offset=$(($o))
	fi

	# Check in boundaries
	let fCount=${#locations[@]}
	if [ $offset -ge 0 -a $offset -lt $fCount ]; then
	    # Delete backup directory
	    _rw
	    rm -rf $BACKUP_ROOT_DIR/${locations[$offset]} > /dev/null 2>&1
	    
	    # Recreate catalog
	    rm -f $BACKUP_CATALOG > /dev/null 2>&1
	    for n in $(seq 0 $(($fCount - 1))); do
		if [ $n -ne $offset ]; then
	    	    echo "${names[n]}:${locations[n]}" >> $BACKUP_CATALOG
		fi
	    done
	    _ro
	    
	    echo "[OK] ** Backup \"${names[$offset]}\" deleted."
	else
	    echo "[ERR] ** Specified offset is out of boundaries."
	fi
	

    else
	echo "[NONE]"
    fi
}

## Backup/Restore submenu
function MenuBackupRestore() {
    while true; do
	echo -e "\n   Backup/Restore:"
	echo "   --------------"
	echo "   1: List available backups"
	echo "   2: Backup current configuration"
	echo "   3: Restore a backup"
	echo "   4: Delete a backup"
	MenuPrompt
	r=$?
	
	case "$r" in
	    1)
		ListAvailableBackups
		;;

	    2)
		BackupCurrentConfig
		break
		;;

	    3)
		RestoreBackup
		break
		;;

	    4)
		DeleteBackup
		;;

	    113|81)
		break
		;;
	    
	    *)
		echo "[ERR]"
		;;
	esac
    done
}

function ShowModem() {
    # Get the pretty name for the chosen Modem according to the dashboard.
    echo "************************************************************************************************************"
    echo "***                                          Modem Informations                                          ***"
    echo "************************************************************************************************************"
    if [ -f '/etc/dstar-radio.mmdvmhost' ]; then
	# Get the modem that the user has selected.
	modemSelected=$(grep 'Hardware=' /etc/dstar-radio.mmdvmhost)
	modemSelected=${modemSelected#*=}
	
	# Get the user friendly version of the selected Modem.
	modemSelectedHuman=$(grep value=\"${modemSelected}\" /var/www/dashboard/admin/configure.php | head -n 1)
	modemSelectedHuman=${modemSelectedHuman#*\">}
	modemSelectedHuman=${modemSelectedHuman::-9}
	echo " Selected Modem:     ${modemSelectedHuman}"
    fi
    
    # Get the Modem info from the Log
    numLogs=$(ls -1rt /var/log/pi-star/MMDVM-*.log 2>/dev/null | wc -l)
    if [[ ${numLogs} -gt 0 ]]; then
	# Get the physically connected modem from the logs
	modemLog=$(tac $(ls -1rt /var/log/pi-star/MMDVM-*.log | tail -n1 ) | grep "protocol" -m 1 | sed -n 's/description: /&\n/;s/.*\n//p')
	echo " Connected Hardware: ${modemLog}"
	
	# Get the TCXO data
	if [[ ${modemLog} == *"MHz"* ]]; then
	    tcxoData=$(echo ${modemLog} | awk '{print $3}')
	    echo " TCXO Value:         ${tcxoData}"
	fi
    fi
    echo "************************************************************************************************************"
}

## Modem tools submenu
function ModemTools() {
    while true; do
	echo -e "\n"
	ShowModem
	
	echo -e "\n   Modem Tools:"
	echo "   -----------"
	echo "                *** MMDVM Devices ***"
	echo "   1: Flash a HS_HAT (14.7456MHz TCXO) connected to GPIO"
	echo "   2: Flash a HS_HAT (12.2880MHz TCXO) connected to GPIO"
	echo "   3: Flash a HS_DUAL_HAT (14.7456MHz TCXO) connected to GPIO"
	echo "   4: Flash a HS_DUAL_HAT (12.2880MHz TCXO) connected to GPIO"
	echo "   5: Flash a HS_HAT_AMBE (14.7456MHz TCXO) connected to GPIO"
	echo "   6: Resets HS_HAT or HS_DUAL_HAT"
	echo "               *** ZUMSpot Devices ***"
	echo "   7: Flash a ZUMSpot connected to GPIO"
	echo "   8: Flash a ZUMSpot duplex connected to GPIO"
	echo "   9: Flash a ZUMSpot USB Key"
	echo "   10: Flash a USB Connected Libre Modem"
	echo "             *** MMDVM_HS Nano Devices ***"
	echo "   11: Flash an Nano HS board connected to GPIO"
	echo "   12: Flash HS_DUAL_HAT (VR2VYE) connected to GPIO"
	echo "             *** BD7KLE/BG3MDO Devices ***"
	echo "   13: Flash a UHF2018 board connected to GPIO"
	echo "   14: Flash a UHF302018 board connected to GPIO"
	echo "   15: Flash a VHF302018 board connected to GPIO"
	echo "                   *** General ***"
	echo "   16: MMDVM Calibration"
	MenuPrompt
	r=$?
	
	case "$r" in
	    1)
		/usr/local/sbin/pistar-mmdvmhshatflash hs_hat
		break
		;;
	    2)
		/usr/local/sbin/pistar-mmdvmhshatflash hs_hat-12mhz
		break
		;;

	    3)
		/usr/local/sbin/pistar-mmdvmhshatflash hs_dual_hat
		break
		;;

	    4)
		/usr/local/sbin/pistar-mmdvmhshatflash hs_dual_hat-12mhz
		break
		;;

	    5)
		/usr/local/sbin/pistar-mmdvmhshatflash hs_hat_ambe
		break
		;;

	    6)
		/usr/local/sbin/pistar-mmdvmhshatreset
		break
		;;
	    
	    7)
		/usr/local/sbin/pistar-zumspotflash rpi
		break
		;;

	    8)
		/usr/local/sbin/pistar-zumspotflash rpi_duplex
		break
		;;

	    9)
		/usr/local/sbin/pistar-zumspotflash usb
		break
		;;

	    10)
		/usr/local/sbin/pistar-zumspotflash libre
		break
		;;

	    11)
		/usr/local/sbin/pistar-vyehsflash nano_hs
		break
		;;

	    12)
		/usr/local/sbin/pistar-vyehsflash hs_dual_hat
		break
		;;
	    
	    13)
		/usr/local/sbin/pistar-mdoflash uhf
		break
		;;

	    14)
		/usr/local/sbin/pistar-mdoflash uhf2
		break
		;;

	    15)
		/usr/local/sbin/pistar-mdoflash vhf
		break
		;;

	    16)
		/usr/local/sbin/pistar-mmdvmcal
		break
		;;
	    
	    113|81)
		break
		;;
	    
	    *)
		echo "[ERR]"
		;;
	esac
    done
}

## Display live logs
function LiveLogs() {
    trap "CtrlC_NOOP" INT
    echo "******************************"
    echo "*** Press <CTRL>-C to exit ***"
    echo "******************************"
    sleep 2s
    tail -f /var/log/pi-star/*.log
    trap "CtrlC" INT
}

## System submenu
function MenuSystem() {
    while true; do
	echo -e "\n   System:"
	echo "   ------"
	echo "   1: Pi-Star Update"
	echo "   2: Pi-Star Upgrade"
	echo "   3: Modem Tools"
	echo "   4: Live logs"
	echo "   5: System Reboot"
	echo "   6: System Shutdown"
	MenuPrompt
	r=$?
	
	case "$r" in
	    1)
		/usr/local/sbin/pistar-update
		break
		;;

	    2)
		/usr/local/sbin/pistar-upgrade
		break
		;;

	    3)
		ModemTools
		break
		;;
	    4)
		LiveLogs
		break;
		;;

	    5)
		echo "*** Rebooting now ***"
		shutdown --no-wall -r now
		exit 0
		;;

	    6)
		echo "*** Shutting down now ***"
		shutdown --no-wall -P now
		exit 0
		;;
	    
	    113|81)
		break
		;;
	    
	    *)
		echo "[ERR]"
		;;
	esac
    done
}

## Sanity configuration checking
function SanityCheck() {
    if [ ! -d $BACKUP_ROOT_DIR ]; then
	_rw
	mkdir -p $BACKUP_ROOT_DIR
	_ro
    else
	RebuildBackupCatalog
    fi
}

## Main
if [[ $# -eq 0 ]]; then
    trap "CtrlC" INT
fi

SanityCheck


# Command line arguments
if [[ $# -gt 0 ]]; then
    
    case "$1" in
	"backup")
	    BackupCurrentConfig "$2"
	    ;;
	"restore")
	    RestoreBackup "$2"
	    ;;
	"list")
	    ListAvailableBackups "count"
	    ;;
	*)
	    echo "[ERR]"
	    ;;
    esac
    
else # Interactive
    
    let loop=1
    while [ $loop == 1 ]; do
	echo "`basename $0` v$VERSION_STRING"
	echo -e "\n   Main Menu:"
	echo "   ---------"
	echo "   1: Services"
	echo "   2: Backup/Restore"
	echo "   3: System"
	MenuPrompt
	r=$?
	
	case "$r" in
	    1)
		MenuServices
		;;
	    
	    2)
		MenuBackupRestore
		;;
	    
	    3)
		MenuSystem
		;;
	    
	    113|81)
		let loop=0
		;;
	    
	    *)
		echo "[ERR]"
		;;
	esac
    done
    
fi
exit 0
