#!/bin/bash
#
##############################################################################
#                                                                            #
#                          Pi-Star MMDVMCal Tool                             #
#                                                                            #
#     Version 1.0, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#                 Make it simple to run MMDVMCal on Pi-Star.                 #
#                      Orrigional suggestion by "mrickey"                    #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Get the modem port from /etc/mmdvmhost
mmdvmModem=$(grep -m 1 'Port' /etc/mmdvmhost | awk -F "=" '/Port/ {print $2}')

# Make the disk RW
#mount -o remount,rw /

# Stop the services
#systemctl stop pistar-watchdog.timer
#systemctl stop pistar-watchdog
#systemctl stop mmdvmhost.timer
#systemctl stop mmdvmhost

# Run MMDVMCal
echo '/usr/local/bin/MMDVMCal ${mmdvmModem}'

# Set the disk back to RO on MMDVMCal exit
#mount -o remount,rw /

# Start the services
#systemctl start pistar-watchdog.timer
#systemctl start pistar-watchdog
#systemctl start mmdvmhost.timer
#systemctl start mmdvmhost
