#!/bin/bash
# Reconfigure/Reconnect WIFI
#
#rpi-rw:
xro=$(sed -n "s/\/dev\/.* \/ ext4 \(r[ow]\).*/\1/p" /proc/mounts)
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,rw /
fi
#
logger -t "[$$]" "Pi-Star --> Wifi Reconnect initiated <--"
sudo wpa_cli reconfigure wlan0
sudo ifdown wlan0
sleep 3
sudo ifup wlan0
sudo wpa_cli scan
#
#rpi-ro:
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,rw /
fi
