#!/bin/bash
#
##############################################################################
#                                                                            #
#                         Pi-Star Find Modem Tool.                           #
#                                                                            #
#     Version 1.0, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#              Make it simple to find the attached MMDVM Modem               #
#                                                                            #
##############################################################################
#
# Kill any MMDVMHost or DStarRepeater processes
if [[ $(/usr/bin/pgrep MMDVMHost) ]]; then
        systemctl stop mmdvmhost > /dev/null 2>&1
        svcRestart=mmdvmhost
fi
if [[ $(/usr/bin/pgrep dstarrepeaterd) ]]; then
        systemctl stop dstarrepeaterd > /dev/null 2>&1
        svcRestart=dstarrepeaterd
fi

# Random Filename
randomFilename=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Find all the possible devices (only looking at /dev/ttyAMA* /dev/ttyACM* and /dev/ttyUSB*)
for modemDevice in $(ls /dev/tty* | grep -E "tty(AMA|ACM|USB|S)."); do
        # Send the MMDVM "Get Version" command to test the ports.
        touch /tmp/${randomFilename}                    # Make the output File
        stty -F ${modemDevice} 115200 raw -echo         # Configure the serial port, its always 115200
        exec 3<${modemDevice}                           # Redirect the output from serial to file descriptor 3
        cat <&3 > /tmp/${randomFilename} &              # Get the content of FD3 and punt it to a file
        PID=$!                                          # Save the PID for the cat command, to dump it later
        echo -en '\xE0\x03\x00' > ${modemDevice}        # Send the "Get Version" command to the port
        sleep 0.2s                                      # Wait for a responce
        kill -9 $PID > /dev/null 2>&1                   # Kill the cat!
        exec 3<&- 1> /dev/stdout 2> /dev/null           # Free up FD3

        # Read the output, and make it pretty for humans...
        if [[ $(cat /tmp/${randomFilename} | wc -c) -ge 1 ]]; then
                # OK we have some output, clean up the modem version string and remove non-printables
                modemData=$(tr -cd '\11\12\15\40-\176' < /tmp/${randomFilename} | sed 's/^.MMDVM/MMDVM/g')

                # OK we have some output, format it into somthing useful.
                if [[ $(grep "MMDVM_HS" /tmp/${randomFilename}) && ${modemDevice} == *"ttyAMA"* ]]; then
                        echo -e "Detected MMDVM_HS (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM_HS" /tmp/${randomFilename}) && ${modemDevice} == *"ttyS"* ]]; then
                        echo -e "Detected MMDVM_HS (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM_HS" /tmp/${randomFilename}) && ${modemDevice} == *"ttyACM"* ]]; then
                        echo -e "Detected MMDVM_HS (USB)  : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM_HS" /tmp/${randomFilename}) && ${modemDevice} == *"ttyUSB"* ]]; then
                        echo -e "Detected MMDVM_HS (USB)  : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM" /tmp/${randomFilename}) && ${modemDevice} == *"ttyAMA"* ]]; then
                        echo -e "Detected MMDVM    (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM" /tmp/${randomFilename}) && ${modemDevice} == *"ttyS"* ]]; then
                        echo -e "Detected MMDVM    (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM" /tmp/${randomFilename}) && ${modemDevice} == *"ttyACM"* ]]; then
                        echo -e "Detected MMDVM    (USB)  : ${modemDevice} (${modemData})"
                elif [[ $(grep "MMDVM" /tmp/${randomFilename}) && ${modemDevice} == *"ttyUSB"* ]]; then
                        echo -e "Detected MMDVM    (USB)  : ${modemDevice} (${modemData})"
                elif [[ $(grep "DVMEGA" /tmp/${randomFilename}) && ${modemDevice} == *"ttyAMA"* ]]; then
                        echo -e "Detected DVMEGA   (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "DVMEGA" /tmp/${randomFilename}) && ${modemDevice} == *"ttyS"* ]]; then
                        echo -e "Detected DVMEGA   (GPIO) : ${modemDevice} (${modemData})"
                elif [[ $(grep "DVMEGA" /tmp/${randomFilename}) && ${modemDevice} == *"ttyACM"* ]]; then
                        echo -e "Detected DVMEGA   (USB)  : ${modemDevice} (${modemData})"
                elif [[ $(grep "DVMEGA" /tmp/${randomFilename}) && ${modemDevice} == *"ttyUSB"* ]]; then
                        echo -e "Detected DVMEGA   (USB)  : ${modemDevice} (${modemData})"
                fi
        fi

        # Dump the temp file we used
        rm -rf /tmp/${randomFilename}
done

# Restart the service(s) if I stopped them
if [[ -v svcRestart ]]; then
        systemctl start ${svcRestart} > /dev/null 2>&1
fi
