#!/bin/bash
#
##############################################################################
#                                                                            #
#                          Pi-Star TGIF API Tool                             #
#                                                                            #
#     Version 0.1, Code, Design and Development by Andy Taylor (MW0MWZ).     #
#                                                                            #
#    Added the option to manage static/dynamic TalkGroups and to be able     #
#                        to drop the current QSO.                            #
#                                                                            #
##############################################################################
#
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Setup some variables
APIURL="http://tgif.network:5040/api/sessions/update/"

# Figure out the DMR ID
DMRNetHost=$(sed -n -e '/\[DMR Network\]/,/\[System Fusion Network\]/p' /etc/mmdvmhost | grep "Address=" | awk -F "=" '/Address=/ {print $2}')
if [[ "${DMRNetHost}" == "127.0.0.1" ]]; then
        # Using DMRGateway
        DMRID=$(sed -n -e '/DMR Network 4/,/DMR Network 5/p' /etc/dmrgateway | grep "Id" | awk -F "=" '/Id=/ {print $2}')
else
        # Using MMDVMHost
        DMRMMDVMHostID=$(sed -n -e '/\[DMR\]/,/\[System Fusion\]/p' /etc/mmdvmhost | grep "Id" | awk -F "=" '/Id=/ {print $2}')
        if [[ ${DMRMMDVMHostID} ]]; then
                # ID Specified in the DMR section
                DMRID=${DMRMMDVMHostID}
        else
                # No ID in the DMR Section
                DMRID=$(grep -m 1 'Id=' /etc/mmdvmhost | tac | tail -1 | awk -F "=" '/Id/ {print $2}')
        fi
fi

DMRID="${DMRID//[!0-9]/}"

if [ -z "$1" ]
then
	echo "NOTE: In the below example commands, please replace {TG Number} with"
	echo "the number of the Talkgroup you wish to link. For example 31665."
	echo ""
	echo "Similarly the {TimeSlot} should be replaced with your target time"
	echo "slot number, either 1 or 2"
	echo ""
	echo "To set the static TG:            pistar-tgifapi link {TG Number} {TimeSlot Number}"
	echo "To remove the static TG:         pistar-tgifapi clear {TimeSlot Number}"
	echo ""
	exit 0
fi

case ${1} in
dmrid)
	echo "Your DMR ID is: ${DMRID}"
	exit 0
;;
link)
	# Check that the variable for TalkGroup has been passed
	if [ -z "$2" ]
	then
		echo "No TG Specfified"
		exit 0
	else
		targetTG=$2
	fi
	# Check that the variable to TimeSlot has been passed
	if [ -z "$3" ]
	then
		TS="1"
	else
		TS=$3
	fi

	APIURL="${APIURL}${DMRID}/$((${TS}-1))/${targetTG}"
	REQUEST="Set TG ${targetTG} to TimeSlot ${TS} for DMR ID ${DMRID}"
;;
clear)
	# Check that the variable to TimeSlot has been passed
	if [ -z "$2" ]
	then
		TS="1"
	else
		TS=$2
	fi

	APIURL="${APIURL}${DMRID}/$((${TS}-1))/4000"
	REQUEST="Clear TG from TimeSlot ${TS} for DMR ID ${DMRID}"
;;
*)
	echo "ERROR: Unknown Command Specified"
	exit 0
;;
esac


# Do the magic
echo " Request to TGIF API: ${REQUEST}"
RESULT=$(wget -q -O - --user-agent="Pi-Star cli tool for: ${DMRID}" --header="Content-Type: application/x-www-form-urlencoded" "${APIURL}")
if [[ ${RESULT} == 200 ]]; then
	RESULT="OK"
else
	RESULT="Somthing went wrong with this request"
fi
echo "Answer from TGIF API: ${RESULT}"
echo ""
exit 0
